version: "3"

services:
  hdu_library_watcher:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: hdu_library_watcher:latest
    working_dir: /root/HDU_library_watcher
    restart: on-failure