version: "3"

services:
  hdu_library_watcher:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: hdu_library_watcher:latest
    volumes:
      - "/etc/localtime:/etc/localtime"
#    command:
    restart: on-failure